plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.compose)
    id 'maven-publish'
}

group = 'io.github.mjrfusion'
version = '1.0.0-alpha.1'

android {
    namespace 'com.mjrfusion.docxion'
    compileSdk 37

    defaultConfig {
        minSdk 24
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildFeatures {
        compose true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
            withJavadocJar()
        }
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.activity.compose
    implementation libs.androidx.compose.runtime
    implementation libs.androidx.compose.ui
    implementation libs.androidx.webkit
    implementation libs.timber
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release

                pom {
                    name = 'Docxion'
                    description = 'Android document viewer library'
                    url = 'https://github.com/mjrfusion/docxion'

                    licenses {
                        license {
                            name = 'Apache License 2.0'
                            url = 'https://www.apache.org/licenses/LICENSE-2.0'
                        }
                    }

                    developers {
                        developer {
                            id = 'mjrfusion'
                            name = 'MJrFusion'
                        }
                    }

                    scm {
                        connection = 'scm:git:git://github.com/mjrfusion/docxion.git'
                        developerConnection = 'scm:git:ssh://github.com/mjrfusion/docxion.git'
                        url = 'https://github.com/mjrfusion/docxion'
                    }
                }
            }
        }
    }
}